FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS builder

WORKDIR /app

COPY ./ ./
RUN dotnet publish PucSp.DesignPatterns.ConfigurationManager.csproj -c Release -o /publish

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-alpine AS runner

WORKDIR /out
COPY --from=builder ./publish ./

ENTRYPOINT [ "dotnet", "PucSp.DesignPatterns.ConfigurationManager.dll" ]
