FROM microsoft/dotnet:3.0-sdk-alpine AS builder

WORKDIR /app

COPY PucSp.DesignPatterns.HtmlBuilder.csproj ./
RUN dotnet publish PucSp.DesignPatterns.HtmlBuilder.csproj -c Release -o /publish

FROM microsoft/dotnet:3.0-aspnetcore-runtime-alpine AS runner

WORKDIR /app
COPY --from=builder ./publish ./

ENTRYPOINT [ "dotnet", "PucSp.DesignPatterns.HtmlBuilder.dll" ]
